DRIVER="{MySQL}"
DB_SERVER = "localhost"
DATABASE = "paste"
DEBUG = True
SECRET_KEY = 'development key'
USERNAME = 'paste'
PASSWORD = 'pasteuser1'
SALT = "KJAShfdkjalshdfuiagldfjblaf"
MAX_TEXT_LENGTH = 1024
MAX_TITLE_LENGTH = 256
MAX_AUTHOR_LENGTH = 25
SUPPORTED_MODES = ["javascript", "python", "ruby"]
