DRIVER="{MySQL}"
DB_SERVER = "localhost"
DATABASE = "paste"
DEBUG = True
SECRET_KEY = 'development key'
USERNAME = 'paste'
PASSWORD = 'pasteuser1'
SALT = "KJAShfdkjalshdfuiagldfjblaf"
SUPPORTED_MODES = ["javascript", "python", "ruby"]
